name: release

on:
  push:
    tags:
      - "v*"

permissions:
  packages: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build and archive with goreleaser
        run: docker run --rm -v `pwd`:/app -w /app goreleaser/goreleaser --verbose release --clean --skip=announce,publish,validate
      - name: Upload release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view "$TAG_NAME" || gh release create "$TAG_NAME"
          gh release upload "$TAG_NAME" --clobber dist/*.tar.gz dist/*.zip dist/*.sha256
